/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as ApiArtifactRouteImport } from './routes/api/artifact'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiMemoryRouteImport } from './routes/api/memory'
import { Route as ApiShipRouteImport } from './routes/api/ship'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1OpenapiRouteImport } from './routes/api/v1/openapi'
import { Route as ApiV1TransactionsRouteImport } from './routes/api/v1/transactions'
import { Route as ApiV1WalletRouteImport } from './routes/api/v1/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactRoute = ApiArtifactRouteImport.update({
  id: '/api/artifact',
  path: '/api/artifact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryRoute = ApiMemoryRouteImport.update({
  id: '/api/memory',
  path: '/api/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShipRoute = ApiShipRouteImport.update({
  id: '/api/ship',
  path: '/api/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiRoute = ApiV1OpenapiRouteImport.update({
  id: '/api/v1/openapi',
  path: '/api/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TransactionsRoute = ApiV1TransactionsRouteImport.update({
  id: '/api/v1/transactions',
  path: '/api/v1/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1WalletRoute = ApiV1WalletRouteImport.update({
  id: '/api/v1/wallet',
  path: '/api/v1/wallet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/desk': typeof DeskRoute
  '/gifts': typeof GiftsRoute
  '/history': typeof HistoryRoute
  '/tools': typeof ToolsRoute
  '/transfer': typeof TransferRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/ship': typeof ApiShipRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/transactions': typeof ApiV1TransactionsRoute
  '/api/v1/wallet': typeof ApiV1WalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/desk': typeof DeskRoute
  '/gifts': typeof GiftsRoute
  '/history': typeof HistoryRoute
  '/tools': typeof ToolsRoute
  '/transfer': typeof TransferRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/ship': typeof ApiShipRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/transactions': typeof ApiV1TransactionsRoute
  '/api/v1/wallet': typeof ApiV1WalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/desk': typeof DeskRoute
  '/gifts': typeof GiftsRoute
  '/history': typeof HistoryRoute
  '/tools': typeof ToolsRoute
  '/transfer': typeof TransferRoute
  '/api/artifact': typeof ApiArtifactRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/memory': typeof ApiMemoryRoute
  '/api/ship': typeof ApiShipRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi': typeof ApiV1OpenapiRoute
  '/api/v1/transactions': typeof ApiV1TransactionsRoute
  '/api/v1/wallet': typeof ApiV1WalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/desk'
    | '/gifts'
    | '/history'
    | '/tools'
    | '/transfer'
    | '/api/artifact'
    | '/api/mcp'
    | '/api/memory'
    | '/api/ship'
    | '/api/v1/health'
    | '/api/v1/openapi'
    | '/api/v1/transactions'
    | '/api/v1/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/desk'
    | '/gifts'
    | '/history'
    | '/tools'
    | '/transfer'
    | '/api/artifact'
    | '/api/mcp'
    | '/api/memory'
    | '/api/ship'
    | '/api/v1/health'
    | '/api/v1/openapi'
    | '/api/v1/transactions'
    | '/api/v1/wallet'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/desk'
    | '/gifts'
    | '/history'
    | '/tools'
    | '/transfer'
    | '/api/artifact'
    | '/api/mcp'
    | '/api/memory'
    | '/api/ship'
    | '/api/v1/health'
    | '/api/v1/openapi'
    | '/api/v1/transactions'
    | '/api/v1/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  DeskRoute: typeof DeskRoute
  GiftsRoute: typeof GiftsRoute
  HistoryRoute: typeof HistoryRoute
  ToolsRoute: typeof ToolsRoute
  TransferRoute: typeof TransferRoute
  ApiArtifactRoute: typeof ApiArtifactRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiMemoryRoute: typeof ApiMemoryRoute
  ApiShipRoute: typeof ApiShipRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1OpenapiRoute: typeof ApiV1OpenapiRoute
  ApiV1TransactionsRoute: typeof ApiV1TransactionsRoute
  ApiV1WalletRoute: typeof ApiV1WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact': {
      id: '/api/artifact'
      path: '/api/artifact'
      fullPath: '/api/artifact'
      preLoaderRoute: typeof ApiArtifactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory': {
      id: '/api/memory'
      path: '/api/memory'
      fullPath: '/api/memory'
      preLoaderRoute: typeof ApiMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ship': {
      id: '/api/ship'
      path: '/api/ship'
      fullPath: '/api/ship'
      preLoaderRoute: typeof ApiShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi': {
      id: '/api/v1/openapi'
      path: '/api/v1/openapi'
      fullPath: '/api/v1/openapi'
      preLoaderRoute: typeof ApiV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/transactions': {
      id: '/api/v1/transactions'
      path: '/api/v1/transactions'
      fullPath: '/api/v1/transactions'
      preLoaderRoute: typeof ApiV1TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/wallet': {
      id: '/api/v1/wallet'
      path: '/api/v1/wallet'
      fullPath: '/api/v1/wallet'
      preLoaderRoute: typeof ApiV1WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  DeskRoute: DeskRoute,
  GiftsRoute: GiftsRoute,
  HistoryRoute: HistoryRoute,
  ToolsRoute: ToolsRoute,
  TransferRoute: TransferRoute,
  ApiArtifactRoute: ApiArtifactRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiMemoryRoute: ApiMemoryRoute,
  ApiShipRoute: ApiShipRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1OpenapiRoute: ApiV1OpenapiRoute,
  ApiV1TransactionsRoute: ApiV1TransactionsRoute,
  ApiV1WalletRoute: ApiV1WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
